"""Unseen multilingual planner cases, frozen before their first live run.

These cases are acceptance evidence, not a prompt-development corpus. If a
case fails, record the result; do not edit either prompt against this file.
"""


def case(
    question,
    route,
    language,
    *,
    supported=True,
    scope="none",
    base=None,
    select=(),
    filters=(),
    group_by=(),
    order_by=(),
    limit=None,
):
    return {
        "question": question,
        "route": route,
        "language": language,
        "supported": supported,
        "scope": scope,
        "base": base,
        "select": select,
        "filters": filters,
        "group_by": group_by,
        "order_by": order_by,
        "limit": limit,
    }


BLIND_HOLDOUT_CASES = [
    # Structured-only: relational, aggregate, literal-text, and unsupported.
    case(
        "Return the three longest-serving active employees and their hire dates.",
        "sql_only", "en", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None),
                ("employees.hire_date", None)),
        filters=(("employees.employment_status", "eq", "active"),),
        order_by=(("employees.hire_date", None, "asc"),), limit=3,
    ),
    case(
        "For every absence category, calculate average days away.",
        "sql_only", "en", base="absences",
        select=(("absences.absence_type", None), ("absences.days_absent", "avg")),
        group_by=("absences.absence_type",),
    ),
    case(
        "Nenne die E-Mail-Adressen aller Beschäftigten im Vertrieb, deren Gehalt höchstens 75000 beträgt.",
        "sql_only", "de", base="employees",
        select=(("employees.email", None),),
        filters=(("departments.department_name", "eq", "Sales"),
                 ("employees.salary", "lte", 75000)),
    ),
    case(
        "Combien d'employés actifs travaillent aux ressources humaines ?",
        "sql_only", "fr", base="employees",
        select=(("employees.employee_id", "count"),),
        filters=(("employees.employment_status", "eq", "active"),
                 ("departments.department_name", "eq", "HR")),
    ),
    case(
        "Muestra las ausencias no remuneradas de empleados de Ingeniería.",
        "sql_only", "es", base="absences", select=(("absences.*", None),),
        filters=(("absences.absence_type", "eq", "unpaid_vacation"),
                 ("departments.department_name", "eq", "Engineering")),
    ),
    case(
        "ما ميزانية قسم المبيعات؟", "sql_only", "ar", base="departments",
        select=(("departments.budget", None),),
        filters=(("departments.department_name", "eq", "Sales"),),
    ),
    case(
        "Which employees have no manager?", "sql_only", "en", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("employees.manager_id", "is_null", None),),
    ),
    case(
        "Liste les cinq salaires les plus bas avec le nom des employés.",
        "sql_only", "fr", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None),
                ("employees.salary", None)),
        order_by=(("employees.salary", None, "asc"),), limit=5,
    ),
    case(
        "¿Cuántos días de ausencia por enfermedad suman todos los empleados?",
        "sql_only", "es", base="absences",
        select=(("absences.days_absent", "sum"),),
        filters=(("absences.absence_type", "eq", "sick"),),
    ),
    case(
        "Zeige Mitarbeiter, deren Nachname mit S beginnt.",
        "sql_only", "de", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("employees.last_name", "starts_with", "S"),),
    ),
    case(
        "List every paid or unpaid vacation absence ending after 2024-06-30.",
        "sql_only", "en", base="absences", select=(("absences.*", None),),
        filters=(("absences.absence_type", "in", ("paid_vacation", "unpaid_vacation")),
                 ("absences.end_date", "gt", "2024-06-30")),
    ),
    case(
        "من هو مدير الموظفة Alice Müller؟", "sql_only", "ar", base="employees",
        select=(("manager.first_name", None), ("manager.last_name", None)),
        filters=(("employees.first_name", "eq", "Alice"),
                 ("employees.last_name", "eq", "Müller")),
    ),
    case(
        "Affiche les noms et postes des employés qui ne sont pas inactifs.",
        "sql_only", "fr", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None),
                ("employees.job_title", None)),
        filters=(("employees.employment_status", "neq", "inactive"),),
    ),
    case(
        "¿Cuál es el salario máximo en cada departamento?", "sql_only", "es",
        base="employees",
        select=(("departments.department_name", None), ("employees.salary", "max")),
        group_by=("departments.department_name",),
    ),
    case(
        "Return employee names when the review ends with the literal text improvement.",
        "sql_only", "en", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("employees.performance_review", "ends_with", "improvement"),),
    ),
    case(
        "Wie viele bezahlte Urlaubstage hatte Alice Müller insgesamt?",
        "sql_only", "de", base="absences",
        select=(("absences.days_absent", "sum"),),
        filters=(("absences.absence_type", "eq", "paid_vacation"),
                 ("employees.first_name", "eq", "Alice"),
                 ("employees.last_name", "eq", "Müller")),
    ),
    case(
        "Montre les employés embauchés entre le 01.03.2020 et le 30.09.2022.",
        "sql_only", "fr", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("employees.hire_date", "between", ("2020-03-01", "2022-09-30")),),
    ),
    case(
        "Lista todos los departamentos por presupuesto descendente.",
        "sql_only", "es", base="departments",
        select=(("departments.*", None),),
        order_by=(("departments.budget", None, "desc"),),
    ),
    case(
        "اعرض الموظفين الذين يتقاضون 70000 أو 80000.",
        "sql_only", "ar", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("employees.salary", "in", (70000, 80000)),),
    ),
    case(
        "What stock options vest next quarter?", "sql_only", "en",
        supported=False,
    ),

    # Review meaning only: polarity and temporal modality are asserted.
    case("Who receives feedback that they could become an excellent client advocate?",
         "review_semantic", "en", scope="future_potential"),
    case("Wer zeigt derzeit außergewöhnliche Geduld mit schwierigen Kunden?",
         "review_semantic", "de", scope="current_strength"),
    case("Qui doit améliorer sa capacité à déléguer ?",
         "review_semantic", "fr", scope="development_need"),
    case("¿Quién está preparado actualmente para asumir la responsabilidad de un proyecto mayor?",
         "review_semantic", "es", scope="readiness"),
    case("من لديه أدلة إيجابية على القدرة على التكيف؟",
         "review_semantic", "ar", scope="broad_positive"),
    case("Whose review identifies avoiding difficult conversations as an improvement area?",
         "review_semantic", "en", scope="development_need"),
    case("Wer könnte künftig komplexe Verhandlungen leiten?",
         "review_semantic", "de", scope="future_potential"),
    case("Qui démontre actuellement une excellente gestion du temps ?",
         "review_semantic", "fr", scope="current_strength"),
    case("¿Quién muestra potencial para entrenar a otros en el futuro?",
         "review_semantic", "es", scope="future_potential"),
    case("من يحتاج إلى تحسين دقته في العمل؟",
         "review_semantic", "ar", scope="development_need"),
    case("Which people currently demonstrate empathy toward colleagues?",
         "review_semantic", "en", scope="current_strength"),
    case("Wer ist heute bereit, mehr Verantwortung für andere zu übernehmen?",
         "review_semantic", "de", scope="readiness"),
    case("Qui montre actuellement une attitude positive face au changement ?",
         "review_semantic", "fr", scope="current_strength"),
    case("¿Quién podría llegar a destacar en la planificación estratégica?",
         "review_semantic", "es", scope="future_potential"),
    case("من يعمل حاليا بهدوء أثناء الخلافات؟",
         "review_semantic", "ar", scope="current_strength"),
    case("Who gets positive feedback about both creativity and practical execution?",
         "review_semantic", "en", scope="current_strength"),
    case("Bei wem wird mangelnde Priorisierung als Entwicklungsfeld genannt?",
         "review_semantic", "de", scope="development_need"),
    case("Qui possède un potentiel positif en matière de médiation ?",
         "review_semantic", "fr", scope="future_potential"),
    case("¿Quién tiene pruebas positivas de resiliencia profesional?",
         "review_semantic", "es", scope="broad_positive"),
    case("Explain our pension matching rules from employee reviews.",
         "sql_only", "en", supported=False),

    # Hybrid: qualitative evidence combined with trusted structured operations.
    case(
        "Among active employees earning at least 72000, who currently handles conflict constructively?",
        "review_semantic_plus_sql", "en", scope="current_strength", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("employees.employment_status", "eq", "active"),
                 ("employees.salary", "gte", 72000)),
    ),
    case(
        "Nenne die zwei am längsten beschäftigten Mitarbeiter mit nachgewiesener Lernbereitschaft.",
        "review_semantic_plus_sql", "de", scope="current_strength", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        order_by=(("employees.hire_date", None, "asc"),), limit=2,
    ),
    case(
        "Combien d'employés du service commercial ont besoin d'améliorer leur présentation ?",
        "review_semantic_plus_sql", "fr", scope="development_need", base="employees",
        select=(("employees.employee_id", "count"),),
        filters=(("departments.department_name", "eq", "Sales"),),
    ),
    case(
        "Muestra a los empleados contratados entre el 01.04.2019 y el 31.12.2022 que tienen potencial para liderar proyectos.",
        "review_semantic_plus_sql", "es", scope="future_potential", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("employees.hire_date", "between", ("2019-04-01", "2022-12-31")),),
    ),
    case(
        "من بين موظفي الموارد البشرية، من هو مستعد الآن لإدارة فريق؟",
        "review_semantic_plus_sql", "ar", scope="readiness", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("departments.department_name", "eq", "HR"),),
    ),
    case(
        "Return the email addresses of Engineering employees whose reviews show positive evidence of adaptability.",
        "review_semantic_plus_sql", "en", scope="broad_positive", base="employees",
        select=(("employees.email", None),),
        filters=(("departments.department_name", "eq", "Engineering"),),
    ),
    case(
        "Welche aktiven Mitarbeiter unter Frank Neumann brauchen bessere Priorisierung?",
        "review_semantic_plus_sql", "de", scope="development_need", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("manager.first_name", "eq", "Frank"),
                 ("manager.last_name", "eq", "Neumann"),
                 ("employees.employment_status", "eq", "active")),
    ),
    case(
        "Liste les trois employés les moins payés qui démontrent actuellement de l'empathie.",
        "review_semantic_plus_sql", "fr", scope="current_strength", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        order_by=(("employees.salary", None, "asc"),), limit=3,
    ),
    case(
        "¿Cuántos empleados contratados después de 2022 muestran actualmente iniciativa proactiva?",
        "review_semantic_plus_sql", "es", scope="current_strength", base="employees",
        select=(("employees.employee_id", "count"),),
        filters=(("employees.hire_date", "gte", "2023-01-01"),),
    ),
    case(
        "اعرض رواتب موظفي المبيعات الذين لديهم إمكانات مستقبلية في التفاوض.",
        "review_semantic_plus_sql", "ar", scope="future_potential", base="employees",
        select=(("employees.salary", None),),
        filters=(("departments.department_name", "eq", "Sales"),),
    ),
    case(
        "Which employees with unpaid vacation absences are praised for careful planning?",
        "review_semantic_plus_sql", "en", scope="current_strength", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("absences.absence_type", "eq", "unpaid_vacation"),),
    ),
    case(
        "Zeige zuverlässige Mitarbeiter, die nicht in der Personalabteilung arbeiten.",
        "review_semantic_plus_sql", "de", scope="current_strength", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("departments.department_name", "neq", "HR"),),
    ),
    case(
        "Qui, parmi les employés gagnant entre 60000 et 85000, pourrait devenir un bon mentor ?",
        "review_semantic_plus_sql", "fr", scope="future_potential", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("employees.salary", "between", (60000, 85000)),),
    ),
    case(
        "Lista a quienes actualmente resuelven problemas y reportan a Bob Schmidt.",
        "review_semantic_plus_sql", "es", scope="current_strength", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("manager.first_name", "eq", "Bob"),
                 ("manager.last_name", "eq", "Schmidt")),
    ),
    case(
        "من هم الموظفون النشطون الذين يحتاجون إلى مزيد من الثقة؟",
        "review_semantic_plus_sql", "ar", scope="development_need", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("employees.employment_status", "eq", "active"),),
    ),
    case(
        "For each department, count employees with current evidence of strong organization.",
        "review_semantic_plus_sql", "en", scope="current_strength", base="employees",
        select=(("departments.department_name", None), ("employees.employee_id", "count")),
        group_by=("departments.department_name",),
    ),
    case(
        "Wer zeigt Teamfähigkeit und wurde vor dem 15.03.2020 eingestellt?",
        "review_semantic_plus_sql", "de", scope="current_strength", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        filters=(("employees.hire_date", "lt", "2020-03-15"),),
    ),
    case(
        "Donne le seul employé le mieux payé qui est actuellement très attentif aux détails.",
        "review_semantic_plus_sql", "fr", scope="current_strength", base="employees",
        select=(("employees.first_name", None), ("employees.last_name", None)),
        order_by=(("employees.salary", None, "desc"),), limit=1,
    ),
    case(
        "Muestra todos los datos de empleados de Ingeniería con potencial futuro para negociar.",
        "review_semantic_plus_sql", "es", scope="future_potential", base="employees",
        select=(("employees.*", None),),
        filters=(("departments.department_name", "eq", "Engineering"),),
    ),
    case(
        "من يعمل في قسم التسويق ويظهر تعاونا قويا؟",
        "sql_only", "ar", supported=False,
    ),
]

assert len(BLIND_HOLDOUT_CASES) == 60
